---
install:
  - SET PATH=C:\Ruby23-x64\bin;%PATH%
  - gem install bundler --no-document
  - bundle install
build: off
test_script:
  - KITCHEN_YAML=.kitchen.windows.yml bundle exec kitchen test
deploy: off
