---
install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - set KITCHEN_YAML=.kitchen.windows.yml
  - gem install bundler --no-document
  - bundle install
build: off
test_script:
  - bundle exec kitchen test
deploy: off
