---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: install
    run_list:
      - recipe[code_deploy::install_agent]

verifier:
  name: inspec
